from __future__ import annotations

from datetime import date
from typing import Protocol

from overlord.app.read_models import TaskListItem
from overlord.modules.cycles.domain import Cycle, CycleStatus, Milestone, WeeklyOutcome
from overlord.modules.cycles.read_models import CycleDetail, CycleSummary


class TaskListReader(Protocol):
    def list(self, **filters: object) -> list[TaskListItem]: ...


class CycleRepositoryPort(Protocol):
    def create(self, title: str, main_outcome: str, start_date: date, length_weeks: int) -> Cycle: ...
    def get(self, cycle_id: int) -> Cycle | None: ...
    def list(self, status: CycleStatus | None = None, search: str = "") -> list[Cycle]: ...
    def summaries(self, status: CycleStatus | None = None, search: str = "") -> list[CycleSummary]: ...
    def detail(self, cycle_id: int) -> CycleDetail | None: ...
    def active(self) -> CycleDetail | None: ...
    def change_status(self, cycle_id: int, status: CycleStatus) -> Cycle: ...
    def connect_project(self, cycle_id: int, project_id: int) -> None: ...
    def connect_milestone(self, cycle_id: int, milestone_id: int) -> None: ...
    def connect_task(self, cycle_id: int, task_id: int) -> None: ...
    def list_milestones(self) -> list[Milestone]: ...
    def create_milestone(self, cycle_id: int, project_id: int, title: str, definition_of_done: str) -> Milestone: ...
    def set_weekly_outcome(self, cycle_id: int, week_number: int, title: str, definition_of_done: str, status: str) -> WeeklyOutcome: ...
