from __future__ import annotations

from typing import Protocol

from overlord.app.read_models import TaskListItem
from overlord.modules.tasks.domain import Task, TaskLifecycle
from overlord.modules.tasks.read_models import StatusHistoryEntry


class TaskRepositoryPort(Protocol):
    def create(self, project_id: int | None, title: str, lifecycle: TaskLifecycle, **fields: object) -> Task: ...
    def get(self, task_id: int) -> Task | None: ...
    def list(self, **filters: object) -> list[TaskListItem]: ...
    def update(self, task_id: int, **changes: object) -> Task: ...
    def change_lifecycle(self, task_id: int, lifecycle: TaskLifecycle, reason: str | None = None) -> Task: ...
    def status_history(self, task_id: int) -> list[StatusHistoryEntry]: ...
