from __future__ import annotations


ENGLISH_STRINGS = {
    "app.name": "Overlord",
    "nav.dashboard": "Dashboard",
    "nav.tasks": "Tasks",
    "nav.projects": "Projects",
    "nav.cycles": "12-Week Plans",
    "nav.settings": "Settings",
    "nav.expand_sidebar": "Expand sidebar",
    "nav.collapse_sidebar": "Collapse sidebar",
    "common.edit": "Edit",
    "common.edit_named": "Edit {name}",
    "common.complete_task": "Complete task",
    "common.complete_named": "Complete {name}",
    "common.review_status": "Review status",
    "common.metadata_separator": " · ",
    "common.dismiss": "Dismiss",
    "common.error": "Error",
    "common.success": "Success",
    "common.try_again": "Try again",
    "app.not_found.title": "Page not found",
    "app.not_found.description": "This route is not part of Foundation v0.1.",
    "app.not_found.action": "Go to Dashboard",
    "app.route_error.title": "This page could not be loaded.",
    "app.route_error.description": "The rest of Overlord is still available. Try this page again.",
    "app.route_error.id": "Error ID: {error_id}",
    "settings.title": "Settings",
    "settings.subtitle": "Keep appearance and planning preferences consistent on this device.",
    "settings.category": "Settings category",
    "settings.category.appearance": "Appearance",
    "settings.category.planning": "Planning",
    "settings.category.startup": "Startup",
    "settings.appearance.description": "Choose how Overlord looks and how much interface motion it uses.",
    "settings.planning.description": "Set the defaults used when planning weeks and new Cycles.",
    "settings.startup.description": "Choose where Overlord opens and how the Sidebar starts.",
    "settings.theme": "Theme",
    "settings.theme.description": "Follow Windows or use a fixed Light or Dark appearance.",
    "settings.theme.system": "System",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.motion": "Motion enabled",
    "settings.motion.description": "Allow brief interface transitions where they clarify state changes.",
    "settings.reduced_motion": "Reduced motion",
    "settings.reduced_motion.description": "Remove nonessential motion while preserving state feedback.",
    "settings.motion_effective_off": "Reduced motion takes priority when both preferences are enabled.",
    "settings.first_day": "First day of week",
    "settings.first_day.description": "Used for weekly planning and progress boundaries.",
    "settings.first_day.monday": "Monday",
    "settings.first_day.sunday": "Sunday",
    "settings.cycle_length": "Default Cycle length",
    "settings.cycle_length.description": "Pre-fills the length when creating a 12-week plan.",
    "settings.weeks": "weeks",
    "settings.startup_destination": "Startup destination",
    "settings.startup_destination.description": "The first Foundation screen opened from the root route.",
    "settings.sidebar_collapsed": "Start with Sidebar collapsed",
    "settings.sidebar_collapsed.description": "Use the compact icon rail when Overlord starts.",
    "settings.save": "Save Settings",
    "settings.saved": "Settings saved.",
    "settings.save_error": "Settings could not be saved. Review the highlighted values and try again.",
    "dashboard.title": "Dashboard",
    "dashboard.plan_day": "Plan the day",
    "dashboard.today.title": "Today’s Tasks",
    "dashboard.today.capacity": "3 Primary · 4 Secondary",
    "dashboard.today.empty.title": "Nothing is planned for today.",
    "dashboard.today.empty.description": "Choose existing Tasks and decide what deserves your attention.",
    "dashboard.primary": "Primary",
    "dashboard.secondary": "Secondary",
    "dashboard.weekly.title": "Weekly Progress",
    "dashboard.cycle.title": "Current Cycle",
    "dashboard.attention.title": "Needs Attention",
    "dashboard.actual_time": "Actual time: {value}",
    "planning.title": "Daily Planning",
    "planning.subtitle": "Choose existing Tasks and shape a realistic day.",
    "planning.date": "Plan date",
    "planning.load_date": "Load date",
    "planning.find_tasks": "Find Tasks",
    "planning.search": "Search Tasks",
    "planning.source": "Source",
    "planning.project": "Project",
    "planning.all_sources": "All available",
    "planning.current_week": "Current week",
    "planning.overdue": "Overdue",
    "planning.active_cycle": "Active Cycle",
    "planning.primary": "Primary {count}/3",
    "planning.secondary": "Secondary {count}/4",
    "planning.assign_primary": "Assign Primary",
    "planning.assign_secondary": "Assign Secondary",
    "planning.move_up": "Move up",
    "planning.move_down": "Move down",
    "planning.remove": "Remove",
    "planning.save": "Save plan",
    "planning.cancel": "Cancel",
    "planning.no_candidates": "No Tasks match these filters.",
    "planning.empty_group": "No Tasks assigned yet.",
    "tasks.title": "Tasks",
    "tasks.subtitle": "Browse your work, capture something quickly, and add detail only when it helps.",
    "tasks.quick_action": "Quick Task",
    "tasks.results": "Task results",
    "tasks.results_count": "{count} Tasks",
    "tasks.search": "Search Tasks or Projects",
    "tasks.project_filter": "Project",
    "tasks.project_all": "All Projects",
    "tasks.no_project": "No Project",
    "tasks.lifecycle": "Lifecycle",
    "tasks.lifecycle_all": "All lifecycle states",
    "tasks.date_scope": "Date / week",
    "tasks.date_any": "Any date",
    "tasks.date_today": "Today",
    "tasks.date_week": "This week",
    "tasks.date_overdue": "Overdue",
    "tasks.date_unplanned": "Not planned",
    "tasks.importance": "Importance",
    "tasks.urgency": "Urgency",
    "tasks.any": "Any",
    "tasks.important": "Important",
    "tasks.not_important": "Not important",
    "tasks.urgent": "Urgent",
    "tasks.not_urgent": "Not urgent",
    "tasks.attention": "Needs Attention only",
    "tasks.apply_filters": "Apply filters",
    "tasks.reset_filters": "Reset filters",
    "tasks.empty": "No Tasks match these filters.",
    "tasks.quick_title": "Quick Task",
    "tasks.quick_description": "Capture the Task now. Planning it for Today happens separately.",
    "tasks.field_title": "Title",
    "tasks.field_description": "Description",
    "tasks.field_project": "Project (optional)",
    "tasks.more_details": "More details",
    "tasks.fewer_details": "Fewer details",
    "tasks.field_planned_date": "Planned date (optional)",
    "tasks.field_estimate": "Estimate (minutes)",
    "tasks.field_definition": "Definition of Done",
    "tasks.field_next_action": "Next action",
    "tasks.field_blocker_type": "Blocker type",
    "tasks.field_blocker_description": "Blocker information",
    "tasks.create": "Create Task",
    "tasks.cancel": "Cancel",
    "tasks.created": "Task created.",
    "tasks.updated": "Task updated.",
    "tasks.edit_title": "Edit Task",
    "tasks.save": "Save changes",
    "tasks.close": "Close",
    "tasks.lifecycle_section": "Lifecycle",
    "tasks.blockers_section": "Blockers",
    "tasks.planning_history": "Planning history",
    "tasks.status_history": "Status history",
    "tasks.no_planning_history": "No planning history",
    "tasks.no_status_history": "No status changes yet",
    "tasks.open_blocker": "Open blocker",
    "tasks.resolve": "Resolve",
    "tasks.resolution": "Resolution",
    "tasks.resolved": "Resolved",
    "tasks.blocked": "Blocked",
    "tasks.blockers": "{count} blockers",
    "tasks.needs_attention_label": "Needs Attention",
    "tasks.no_today_slot": "No Today slot",
    "tasks.plan_moved": "moved",
    "tasks.plan_original": "original",
    "tasks.status_unset": "unset",
    "tasks.no_reason": "No reason",
    "tasks.date_error": "Date must use YYYY-MM-DD.",
    "tasks.estimate_integer_error": "Estimate must be a whole number of minutes.",
    "projects.title": "Projects",
    "projects.subtitle": "Browse outcomes, see what is moving, and open the work that needs attention.",
    "projects.new_action": "New Project",
    "projects.browse": "Projects",
    "projects.search": "Search Projects",
    "projects.status_filter": "Status",
    "projects.status_all": "All statuses",
    "projects.clear_filters": "Clear filters",
    "projects.results_count": "{count} Projects",
    "projects.empty": "No Projects match these filters.",
    "projects.none_description": "No Projects yet. Create one when a piece of work needs its own outcome, Tasks, and context.",
    "projects.field_title": "Title",
    "projects.field_description": "Description",
    "projects.new_title": "New Project",
    "projects.new_description": "Name the outcome. You can shape milestones and Tasks after capture.",
    "projects.cancel": "Cancel",
    "projects.create": "Create Project",
    "projects.created": "Project created.",
    "projects.updated": "Project updated.",
    "projects.open": "Open",
    "projects.open_tasks": "{count} open Tasks",
    "projects.blocker_count": "{count} open blockers",
    "projects.blocker_one": "1 open blocker",
    "projects.no_blockers": "No open blockers",
    "projects.current_stage": "Current stage",
    "projects.no_stage": "Stage not defined",
    "projects.current_milestone": "Current milestone",
    "projects.no_milestone": "No current milestone",
    "projects.next_action": "Next action",
    "projects.no_next_action": "Next action not defined",
    "projects.not_connected": "Not connected to the active Cycle",
    "projects.cycle_context": "{title} - Week {week} of {length}",
    "projects.progress_unavailable": "Progress unavailable - no eligible Tasks yet.",
    "projects.progress_count": "{completed} of {total} eligible Tasks complete",
    "projects.unavailable": "Project unavailable",
    "projects.back": "All Projects",
    "projects.detail_subtitle": "Project working context",
    "projects.more": "More",
    "projects.lifecycle_title": "Change Project status",
    "projects.lifecycle_note": "Archiving is reversible. No Project data is deleted.",
    "projects.save": "Save",
    "projects.progress": "Progress",
    "projects.actual_time": "Actual time: Not tracked yet",
    "projects.cycle": "Active Cycle",
    "projects.cycle_optional": "Projects remain valid without a Cycle connection.",
    "projects.open_cycle": "Open Cycle",
    "projects.milestone_target": "Target: {date}",
    "projects.blockers_title": "Blockers",
    "projects.blockers_empty": "No open blockers for this Project.",
    "projects.blocker_task": "Task: {task} - opened {date}",
    "projects.tasks_title": "Project Tasks",
    "projects.task_filter": "Task view",
    "projects.tasks_open": "Open",
    "projects.tasks_completed": "Completed",
    "projects.tasks_blocked": "Blocked",
    "projects.tasks_empty_filter": "No Tasks in this view.",
    "projects.tasks_none": "No Tasks in this Project yet.",
    "projects.quick_task": "Quick Task",
    "projects.status.active": "Active",
    "projects.status.on_hold": "On hold",
    "projects.status.completed": "Completed",
    "projects.status.archived": "Archived",
    "cycles.title": "12-Week Plans",
    "cycles.subtitle": "Plan a focused execution period around one meaningful Outcome.",
    "cycles.create_action": "Create Cycle",
    "cycles.browse": "Plans",
    "cycles.search": "Search Cycles",
    "cycles.status_filter": "Status",
    "cycles.status_all": "All statuses",
    "cycles.clear_filters": "Clear filters",
    "cycles.results_count": "{count} Cycles",
    "cycles.empty_filtered": "No Cycles match these filters.",
    "cycles.empty_all": "No 12-week plan yet. Create a focused Cycle when you are ready to organize several weeks around one meaningful Outcome.",
    "cycles.status.draft": "Draft",
    "cycles.status.active": "Active",
    "cycles.status.completed": "Completed",
    "cycles.status.archived": "Archived",
    "cycles.outcome_status.planned": "Planned",
    "cycles.outcome_status.achieved": "Achieved",
    "cycles.outcome_status.partial": "Partial",
    "cycles.outcome_status.not_achieved": "Not achieved",
    "cycles.milestone_status.planned": "Planned",
    "cycles.milestone_status.in_progress": "In progress",
    "cycles.milestone_status.completed": "Completed",
    "cycles.milestone_status.cancelled": "Cancelled",
    "cycles.main_outcome": "Main Outcome",
    "cycles.weekly_progress": "Weekly Outcomes",
    "cycles.connected_projects": "Connected Projects",
    "cycles.next_context": "Next",
    "cycles.open": "Open",
    "cycles.no_projects_compact": "No Projects connected",
    "cycles.no_milestone_compact": "No current Milestone",
    "cycles.week_of": "Week {week} of {length}",
    "cycles.progress_unavailable": "No Weekly Outcomes planned yet.",
    "cycles.progress_fraction": "{achieved} of {planned} planned Weekly Outcomes achieved",
    "cycles.progress_achieved": "{count} achieved",
    "cycles.progress_partial": "{count} partial",
    "cycles.progress_remaining": "{count} remaining",
    "cycles.progress_not_achieved": "{count} not achieved",
    "cycles.progress_unplanned": "{count} unplanned weeks",
    "cycles.create_title": "Create Cycle",
    "cycles.create_subtitle": "Shape the plan first. Nothing is saved until the final step.",
    "cycles.step.identity": "Identity",
    "cycles.step.dates": "Dates",
    "cycles.step.connections": "Connections",
    "cycles.step.weekly": "Weekly Outcomes",
    "cycles.step.review": "Review",
    "cycles.step_label": "{number}. {name}",
    "cycles.field_title": "Cycle title",
    "cycles.field_main_outcome": "Main Outcome",
    "cycles.main_outcome_help": "Describe the one result that would make this Cycle successful.",
    "cycles.title_required": "Cycle title is required.",
    "cycles.outcome_required": "Main Outcome is required.",
    "cycles.field_start": "Start date",
    "cycles.field_length": "Length in weeks",
    "cycles.date_error": "Start date must use YYYY-MM-DD.",
    "cycles.length_error": "Length must be a whole number of weeks.",
    "cycles.ends_value": "Ends {date}",
    "cycles.ends_pending": "Enter a valid start date and Cycle length.",
    "cycles.connections_help": "Connect only the Projects and existing Milestones that belong in this execution period.",
    "cycles.projects_section": "Projects",
    "cycles.projects_unavailable": "No Projects are available to connect.",
    "cycles.milestones_section": "Milestones",
    "cycles.milestones_unavailable": "No existing Milestones are available.",
    "cycles.stage_not_set": "Stage not defined",
    "cycles.unknown_project": "Unknown Project",
    "cycles.weekly_help": "Plan the weeks you understand now. Empty future weeks remain valid.",
    "cycles.week_number": "Week {number}",
    "cycles.week_outcome": "Weekly Outcome",
    "cycles.week_definition": "Definition of Done",
    "cycles.week_definition_required": "Definition of Done is required when an Outcome is planned.",
    "cycles.week_title_required": "Outcome text is required when Definition of Done is provided.",
    "cycles.week_error": "Week {number} needs both an Outcome and Definition of Done.",
    "cycles.length_value": "{count} weeks",
    "cycles.review_projects": "Projects: {value}",
    "cycles.review_milestones": "Milestones: {value}",
    "cycles.review_weekly": "{count} of {length} weeks have planned Outcomes",
    "cycles.review_week": "Week {number}: {title}",
    "cycles.none": "None",
    "cycles.active_conflict": "{title} is already active. This Cycle can be created as Draft, but activation requires resolving the existing active Cycle explicitly.",
    "cycles.cancel": "Cancel",
    "cycles.back": "Back",
    "cycles.continue": "Continue",
    "cycles.create_draft": "Create draft",
    "cycles.create_activate": "Create and activate",
    "cycles.created_draft": "Draft Cycle created.",
    "cycles.created_active": "Active Cycle created.",
    "cycles.unavailable": "Cycle unavailable",
    "cycles.all_cycles": "All 12-Week Plans",
    "cycles.outcome_unplanned": "Outcome not planned yet.",
    "cycles.not_set": "Not set",
    "cycles.edit": "Edit",
    "cycles.edit_week": "Edit Week {number}",
    "cycles.outcome_status": "Outcome status",
    "cycles.save_week": "Save Weekly Outcome",
    "cycles.week_updated": "Weekly Outcome updated.",
    "cycles.lifecycle_title": "Change Cycle status",
    "cycles.lifecycle_note": "Complete and Archive preserve the Cycle and its historical relationships.",
    "cycles.lifecycle_updated": "Cycle status updated.",
    "cycles.save": "Save",
    "cycles.current_week": "Current Week",
    "cycles.week_dates": "Week {number} - {start}-{end}",
    "cycles.connected_work": "Connected work: {projects} Projects - {tasks} open participating Tasks",
    "cycles.no_current_week": "This Cycle is outside its active date range.",
    "cycles.detail_progress": "{achieved} achieved - {partial} partial - {remaining} remaining - {missed} not achieved - {unplanned} unplanned weeks",
    "cycles.full_plan": "Full Cycle Plan",
    "cycles.project_milestone": "Current milestone: {value}",
    "cycles.project_open_tasks": "{count} open Tasks",
    "cycles.open_project": "Open Project",
    "cycles.no_projects": "No Projects connected. This Cycle remains valid.",
    "cycles.no_milestones": "No Milestones connected.",
    "cycles.connected_tasks": "Connected Task Context",
    "cycles.task_counts": "{open} open - {completed} completed - {total} connected",
    "cycles.task_context_note": "Tasks remain canonical Tasks; this is compact Cycle context, not another Tasks page.",
    "cycles.no_tasks": "No Tasks connected to this Cycle.",
    "cycles.more": "More",
}


def ui_text(key: str, **values: object) -> str:
    template = ENGLISH_STRINGS[key]
    return template.format(**values) if values else template
