from __future__ import annotations

from datetime import date
import re


ENGLISH_STRINGS = {
    "app.name": "Overlord",
    "nav.dashboard": "Dashboard",
    "nav.tasks": "My Tasks",
    "nav.projects": "Projects",
    "nav.cycles": "12-Week Plans",
    "nav.settings": "Settings",
    "nav.expand_sidebar": "Expand sidebar",
    "nav.collapse_sidebar": "Collapse sidebar",
    "nav.language": "Language",
    "nav.language.tooltip": "Switch interface language",
    "common.edit": "Edit",
    "common.edit_named": "Edit {name}",
    "common.complete_task": "Complete task",
    "common.complete_named": "Complete {name}",
    "common.review_status": "Review status",
    "common.metadata_separator": " · ",
    "common.dismiss": "Dismiss",
    "common.error": "Error",
    "common.success": "Success",
    "common.try_again": "Try again",
    "common.not_set": "Not set",
    "common.not_tracked_yet": "Not tracked yet",
    "common.minutes_short": "{count} min",
    "common.date_range": "{start} - {end}",
    "profile.display_name": "Denys",
    "profile.menu": "User menu",
    "lifecycle.backlog": "Backlog",
    "lifecycle.planned": "Planned",
    "lifecycle.in_progress": "In progress",
    "lifecycle.paused": "Paused",
    "lifecycle.completed": "Completed",
    "lifecycle.cancelled": "Cancelled",
    "task_board.planned": "Planned",
    "task_board.in_progress": "In Progress",
    "task_board.missed": "Not completed",
    "task_board.needs_attention": "Needs Attention",
    "task_board.completed": "Completed",
    "task_board.archive": "Archive",
    "blocker.type.dependency": "Dependency",
    "blocker.type.decision": "Decision",
    "blocker.type.resource": "Resource",
    "blocker.type.clarity": "Clarity",
    "blocker.type.technical": "Technical",
    "blocker.type.other": "Other",
    "app.not_found.title": "Page not found",
    "app.not_found.description": "This route is not part of Foundation v0.1.",
    "app.not_found.action": "Go to Dashboard",
    "app.route_error.title": "This page could not be loaded.",
    "app.route_error.description": "The rest of Overlord is still available. Try this page again.",
    "app.route_error.id": "Error ID: {error_id}",
    "settings.title": "Settings",
    "settings.subtitle": "Keep appearance and planning preferences consistent on this device.",
    "settings.category": "Settings category",
    "settings.category.appearance": "Appearance",
    "settings.category.planning": "Planning",
    "settings.category.startup": "Startup",
    "settings.appearance.description": "Choose how Overlord looks and how much interface motion it uses.",
    "settings.planning.description": "Set the defaults used when planning weeks and new Cycles.",
    "settings.startup.description": "Choose where Overlord opens and how the Sidebar starts.",
    "settings.theme": "Theme",
    "settings.theme.description": "Follow Windows or use a fixed Light or Dark appearance.",
    "settings.theme.system": "System",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.motion": "Motion enabled",
    "settings.motion.description": "Allow brief interface transitions where they clarify state changes.",
    "settings.reduced_motion": "Reduced motion",
    "settings.reduced_motion.description": "Remove nonessential motion while preserving state feedback.",
    "settings.motion_effective_off": "Reduced motion takes priority when both preferences are enabled.",
    "settings.first_day": "First day of week",
    "settings.first_day.description": "Used for weekly planning and progress boundaries.",
    "settings.first_day.monday": "Monday",
    "settings.first_day.sunday": "Sunday",
    "settings.cycle_length": "Default Cycle length",
    "settings.cycle_length.description": "Pre-fills the length when creating a 12-week plan.",
    "settings.weeks": "weeks",
    "settings.startup_destination": "Startup destination",
    "settings.startup_destination.description": "The first Foundation screen opened from the root route.",
    "settings.sidebar_collapsed": "Start with Sidebar collapsed",
    "settings.sidebar_collapsed.description": "Use the compact icon rail when Overlord starts.",
    "settings.save": "Save Settings",
    "settings.saved": "Settings saved.",
    "settings.save_error": "Settings could not be saved. Review the highlighted values and try again.",
    "settings.validation.language": "Language must be English or Russian.",
    "settings.validation.theme": "Theme mode must be System, Light, or Dark.",
    "settings.validation.cycle_length": "Default cycle length must be between 1 and 52 weeks.",
    "dashboard.title": "Dashboard",
    "dashboard.greeting": "Good morning, {name}",
    "dashboard.tasks_today.one": "You have 1 task today",
    "dashboard.tasks_today.other": "You have {count} tasks today",
    "dashboard.plan_day": "Plan the day",
    "dashboard.today.title": "Today",
    "dashboard.yesterday.title": "Yesterday",
    "dashboard.tomorrow.title": "Tomorrow",
    "dashboard.add_task": "Add Task...",
    "dashboard.add_yesterday_disabled": "Past dates are read-only",
    "dashboard.empty_day": "No tasks",
    "dashboard.open_task": "Open details for {name}",
    "dashboard.toggle_task": "Change completion for {name}",
    "dashboard.drag_task": "Drag to reorder {name}",
    "dashboard.today.empty": "No tasks scheduled for today.",
    "dashboard.today.capacity": "3 Primary · 4 Secondary",
    "dashboard.today.empty.title": "Nothing is planned for today.",
    "dashboard.today.empty.description": "Choose existing Tasks and decide what deserves your attention.",
    "dashboard.primary": "Primary",
    "dashboard.secondary": "Secondary",
    "dashboard.weekly.title": "Weekly Progress",
    "dashboard.cycle.title": "Current Cycle",
    "dashboard.attention.title": "Needs Attention",
    "dashboard.actual_time": "Actual time: {value}",
    "dashboard.execution_score": "Execution Score",
    "dashboard.completed_planned": "Completed / planned",
    "dashboard.active_time": "Active Time",
    "dashboard.total_time": "Total Time",
    "dashboard.duration.hours": "{hours}h",
    "dashboard.duration.hours_minutes": "{hours}h {minutes}m",
    "dashboard.duration.minutes": "{minutes}m",
    "dashboard.current_outcome": "Current Outcome: {value}",
    "dashboard.next_action": "Next: {value}",
    "dashboard.week_of": "Week {week} of {length}",
    "dashboard.days_remaining": "{count} days remaining",
    "dashboard.next_milestone": "Next milestone: {value}",
    "dashboard.open_cycle": "Open cycle",
    "dashboard.no_active_cycle": "No active Cycle yet.",
    "dashboard.create_plan": "Create a 12-week plan",
    "dashboard.review": "Review",
    "dashboard.weekly_tooltip": "{day}: {completed} completed of {planned} planned",
    "weather.high_low": "H: {high}°C L: {low}°C",
    "weather.condition.sunny": "Sunny",
    "weather.condition.rainy": "Rainy",
    "weather.condition.cloudy": "Cloudy",
    "weather.condition.snowy": "Snowy",
    "weather.condition.mainly_clear": "Mainly clear",
    "weather.condition.partly_cloudy": "Partly cloudy",
    "weather.condition.overcast": "Overcast",
    "weather.condition.fog": "Fog",
    "weather.condition.rime_fog": "Rime fog",
    "weather.condition.light_drizzle": "Light drizzle",
    "weather.condition.drizzle": "Drizzle",
    "weather.condition.heavy_drizzle": "Heavy drizzle",
    "weather.condition.freezing_drizzle": "Freezing drizzle",
    "weather.condition.heavy_freezing_drizzle": "Heavy freezing drizzle",
    "weather.condition.light_rain": "Light rain",
    "weather.condition.rain": "Rain",
    "weather.condition.heavy_rain": "Heavy rain",
    "weather.condition.freezing_rain": "Freezing rain",
    "weather.condition.heavy_freezing_rain": "Heavy freezing rain",
    "weather.condition.light_snow": "Light snow",
    "weather.condition.heavy_snow": "Heavy snow",
    "weather.condition.snow_grains": "Snow grains",
    "weather.condition.light_rain_showers": "Light rain showers",
    "weather.condition.rain_showers": "Rain showers",
    "weather.condition.heavy_rain_showers": "Heavy rain showers",
    "weather.condition.snow_showers": "Snow showers",
    "weather.condition.heavy_snow_showers": "Heavy snow showers",
    "weather.condition.thunderstorm": "Thunderstorm",
    "weather.condition.thunderstorm_hail": "Thunderstorm with hail",
    "weather.condition.heavy_thunderstorm_hail": "Severe thunderstorm with hail",
    "weather.unavailable": "Weather unavailable",
    "weather.visual_label": "Animated {condition} weather",
    "weather.icon_label": "{condition} weather",
    "weather.select_day": "Show weather for {day}",
    "dashboard.reason.open_blocker": "Open blocker",
    "dashboard.reason.carried_over": "Carried over {count} times",
    "dashboard.reason.no_update": "No update for seven days",
    "dashboard.reason.primary_next_action": "Primary task needs a next action",
    "dashboard.reason.legacy_status": "Legacy status requires review",
    "planning.title": "Daily Planning",
    "planning.subtitle": "Choose existing Tasks and shape a realistic day.",
    "planning.date": "Plan date",
    "planning.load_date": "Load date",
    "planning.find_tasks": "Find Tasks",
    "planning.search": "Search Tasks",
    "planning.source": "Source",
    "planning.project": "Project",
    "planning.all_sources": "All available",
    "planning.current_week": "Current week",
    "planning.overdue": "Overdue",
    "planning.active_cycle": "Active Cycle",
    "planning.primary": "Primary {count}/3",
    "planning.secondary": "Secondary {count}/4",
    "planning.assign_primary": "Assign Primary",
    "planning.assign_secondary": "Assign Secondary",
    "planning.move_up": "Move up",
    "planning.move_down": "Move down",
    "planning.remove": "Remove",
    "planning.save": "Save plan",
    "planning.cancel": "Cancel",
    "planning.no_candidates": "No Tasks match these filters.",
    "planning.empty_group": "No Tasks assigned yet.",
    "planning.date_error": "Plan date must use YYYY-MM-DD.",
    "planning.capacity_full": "{group} capacity is already full.",
    "planning.definition_required": "Definition of Done is required before assigning a Primary Task.",
    "planning.today_plan": "Today's Plan",
    "tasks.title": "My Tasks",
    "tasks.subtitle": "Browse your work, capture something quickly, and add detail only when it helps.",
    "tasks.workspace_subtitle": "Plan every Task here. Dashboard shows today's honest slice.",
    "tasks.new": "New Task",
    "tasks.view.kanban": "Kanban",
    "tasks.view.week": "Week",
    "tasks.view.month": "Month",
    "tasks.add_planned": "Add without date",
    "tasks.add_today": "Add for today",
    "tasks.column_empty": "No Tasks in this column.",
    "tasks.drag_task": "Drag to move this Task",
    "tasks.drag_column": "Drag to reorder this column",
    "tasks.moved": "Task moved.",
    "tasks.add_to_date": "Add Task to {date}",
    "tasks.day_empty": "No Tasks",
    "tasks.previous": "Previous",
    "tasks.today": "Today",
    "tasks.next": "Next",
    "tasks.expand_date_navigation": "Expand {view} navigation",
    "tasks.collapse_date_navigation": "Collapse {view} navigation",
    "tasks.calendar.week_title": "{start} - {end}",
    "tasks.quick_action": "Quick Task",
    "tasks.results": "Task results",
    "tasks.results_count": "{count} Tasks",
    "tasks.search": "Search Tasks or Projects...",
    "tasks.add_section": "Add section",
    "tasks.column_add_unavailable": "This derived column cannot create a Task directly",
    "tasks.project_filter": "Project",
    "tasks.project_all": "All Projects",
    "tasks.no_project": "No Project",
    "tasks.lifecycle": "Lifecycle",
    "tasks.lifecycle_all": "All lifecycle states",
    "tasks.date_scope": "Date / week",
    "tasks.date_any": "Any date",
    "tasks.date_today": "Today",
    "tasks.date_week": "This week",
    "tasks.date_overdue": "Overdue",
    "tasks.date_unplanned": "Not planned",
    "tasks.importance": "Importance",
    "tasks.urgency": "Urgency",
    "tasks.any": "Any",
    "tasks.important": "Important",
    "tasks.not_important": "Not important",
    "tasks.urgent": "Urgent",
    "tasks.not_urgent": "Not urgent",
    "tasks.attention": "Needs Attention only",
    "tasks.apply_filters": "Apply filters",
    "tasks.reset_filters": "Reset filters",
    "tasks.empty": "No Tasks match these filters.",
    "tasks.quick_title": "Create Task",
    "tasks.quick_description": "Capture the Task now. Configure it later if necessary.",
    "tasks.details_title": "Task Details",
    "tasks.details_status": "Task status",
    "tasks.details_blocked": "Blocked",
    "tasks.delete": "Delete",
    "tasks.delete_tooltip": "Delete Task",
    "tasks.delete_confirm_title": "Delete task?",
    "tasks.delete_confirm_body": "This action cannot be undone.",
    "tasks.remove_deadline": "Remove deadline",
    "tasks.completion_state": "Completed",
    "tasks.create_title": "Create Task",
    "tasks.creation_mode": "Creation state",
    "tasks.creation.normal": "Planned",
    "tasks.creation.draft": "Draft",
    "tasks.create_save": "Save",
    "tasks.date": "Date",
    "tasks.date_picker.choose_day": "Choose day {day}",
    "tasks.deadline_time": "Deadline time",
    "tasks.projects": "Projects",
    "tasks.projects_count.one": "1 Project",
    "tasks.projects_count.other": "{count} Projects",
    "tasks.projects_none": "No Projects are available.",
    "tasks.projects_limit": "A Task may belong to at most 4 Projects.",
    "tasks.project_stage": "PS-{project}",
    "tasks.project_stage_none": "No Stage",
    "tasks.estimated_time": "Estimated Time",
    "tasks.total_time": "Total Time",
    "tasks.active_time": "Active Time",
    "tasks.complete_title": "Complete Task",
    "tasks.complete_subtitle": "Add the time spent on this task.",
    "tasks.complete_success": "Task completed.",
    "tasks.estimate_hours": "Hours",
    "tasks.estimate_minutes": "Minutes",
    "tasks.estimate_hour_suffix": "h",
    "tasks.estimate_minute_suffix": "min",
    "tasks.estimate_nonnegative": "Hours and minutes must be non-negative whole numbers.",
    "tasks.estimate_minute_range": "Minutes must be between 0 and 59.",
    "tasks.duration_nonnegative": "{field} hours and minutes must be non-negative whole numbers.",
    "tasks.duration_positive": "{field} must be greater than zero.",
    "tasks.checklist": "Checklist",
    "tasks.remove_checklist": "Remove checklist",
    "tasks.add_checklist": "Add checklist",
    "tasks.add_checklist_item": "Add item",
    "tasks.add_checklist_child": "Add child item",
    "tasks.remove_checklist_item": "Remove checklist item",
    "tasks.checklist_item": "Checklist item",
    "tasks.checklist_progress": "{percent}%",
    "tasks.when": "When",
    "tasks.when.today": "Today",
    "tasks.when.tomorrow": "Tomorrow",
    "tasks.when.this_week": "This week",
    "tasks.when.no_date": "No date",
    "tasks.when.choose_date": "Choose date",
    "tasks.custom_date": "Date",
    "tasks.date_hint": "DD.MM.YYYY",
    "tasks.human_date_error": "Date must use DD.MM.YYYY.",
    "tasks.open_calendar": "Open calendar",
    "tasks.choose_date": "Choose date",
    "tasks.advanced_options": "+ Advanced options",
    "tasks.hide_advanced_options": "− Advanced options",
    "tasks.time": "Time",
    "tasks.not_set": "Not set",
    "tasks.set_time": "Set time",
    "tasks.choose_time": "Choose time",
    "tasks.deadline": "Deadline",
    "tasks.set_deadline": "Set deadline",
    "tasks.deadline_date": "Deadline date",
    "tasks.estimate.15": "15 min",
    "tasks.estimate.30": "30 min",
    "tasks.estimate.60": "1 hour",
    "tasks.estimate.custom": "Custom",
    "tasks.estimate_custom": "Custom estimate (minutes)",
    "tasks.priority": "Priority",
    "tasks.schedule_section": "Schedule",
    "tasks.details_section": "Details",
    "tasks.connections_section": "Connections",
    "tasks.no_cycles": "No 12-week Cycles are available.",
    "tasks.until_time": "until {time}",
    "task_card.time_range": "{start} to {end}",
    "tasks.field_title": "Title",
    "tasks.field_description": "Description",
    "tasks.field_project": "Project (optional)",
    "tasks.more_details": "More details",
    "tasks.fewer_details": "Fewer details",
    "tasks.field_planned_date": "Planned date (optional)",
    "tasks.field_start_date": "Start date (optional)",
    "tasks.field_start_time": "Start time",
    "tasks.field_end_date": "End date (optional)",
    "tasks.field_end_time": "End time",
    "tasks.field_deadline": "Deadline (optional)",
    "tasks.field_estimate": "Estimate (minutes)",
    "tasks.field_definition": "Definition of Done",
    "tasks.field_next_action": "Next action",
    "tasks.field_blocker_type": "Blocker type",
    "tasks.field_blocker_description": "Blocker information",
    "tasks.create": "Create Task",
    "tasks.cancel": "Cancel",
    "tasks.created": "Task created.",
    "tasks.updated": "Task updated.",
    "tasks.edit_title": "Edit Task",
    "tasks.save": "Save changes",
    "tasks.close": "Close",
    "tasks.lifecycle_section": "Lifecycle",
    "tasks.blockers_section": "Blockers",
    "tasks.planning_history": "Planning history",
    "tasks.status_history": "Status history",
    "tasks.no_planning_history": "No planning history",
    "tasks.no_status_history": "No status changes yet",
    "tasks.open_blocker": "Open blocker",
    "tasks.resolve": "Resolve",
    "tasks.resolution": "Resolution",
    "tasks.resolved": "Resolved",
    "tasks.blocked": "Blocked",
    "tasks.blockers": "{count} blockers",
    "tasks.needs_attention_label": "Needs Attention",
    "tasks.no_today_slot": "No Today slot",
    "tasks.plan_moved": "moved",
    "tasks.plan_original": "original",
    "tasks.status_unset": "unset",
    "tasks.no_reason": "No reason",
    "tasks.reason.changed_editor": "Changed in Task editor",
    "tasks.reason.completed": "Completed",
    "tasks.date_error": "Date must use YYYY-MM-DD.",
    "tasks.time_error": "Time must use HH:MM.",
    "tasks.datetime_error": "Deadline must use YYYY-MM-DD HH:MM.",
    "tasks.estimate_integer_error": "Estimate must be a whole number of minutes.",
    "projects.title": "Projects",
    "projects.subtitle": "Browse outcomes, see what is moving, and open the work that needs attention.",
    "projects.new_action": "New Project",
    "projects.browse": "Projects",
    "projects.search": "Search Tasks or Projects...",
    "projects.filter_project": "Project",
    "projects.filter_projects": "Projects",
    "projects.status_filter": "Status",
    "projects.status_all": "All statuses",
    "projects.clear_filters": "Clear filters",
    "projects.reset": "Reset",
    "projects.results_count": "{count} Projects",
    "projects.empty": "No Projects match these filters.",
    "projects.none_description": "No Projects yet. Create one when a piece of work needs its own outcome, Tasks, and context.",
    "projects.field_title": "Project name",
    "projects.field_description": "Description",
    "projects.new_title": "New Project",
    "projects.new_description": "Name the outcome. You can shape milestones and Tasks after capture.",
    "projects.cancel": "Cancel",
    "projects.create": "Create Project",
    "projects.created": "Project created.",
    "projects.updated": "Project updated.",
    "projects.open": "Open",
    "projects.add_task": "Add Task to Project",
    "projects.open_tasks": "{count} open Tasks",
    "projects.blocker_count": "{count} open blockers",
    "projects.blocker_one": "1 open blocker",
    "projects.no_blockers": "No open blockers",
    "projects.current_stage": "Current stage",
    "projects.no_stage": "Stage not defined",
    "projects.current_milestone": "Current milestone",
    "projects.no_milestone": "No current milestone",
    "projects.next_action": "Next action",
    "projects.no_next_action": "Next action not defined",
    "projects.not_connected": "Not connected to the active Cycle",
    "projects.cycle_context": "{title} - Week {week} of {length}",
    "projects.progress_unavailable": "Progress unavailable - no eligible Tasks yet.",
    "projects.progress_count": "{completed} of {total} eligible Tasks complete",
    "projects.unavailable": "Project unavailable",
    "projects.back": "All Projects",
    "projects.detail_subtitle": "Project working context",
    "projects.more": "More",
    "projects.back_to_projects": "Back to Projects",
    "projects.tab.overview": "Overview",
    "projects.tab.plan": "Plan",
    "projects.tab.tasks": "Tasks",
    "projects.tab.notes": "Notes & Files",
    "projects.tab.archive": "Archive",
    "projects.lifecycle_title": "Change Project status",
    "projects.lifecycle_note": "Archiving is reversible. No Project data is deleted.",
    "projects.save": "Save",
    "projects.progress": "Progress",
    "projects.actual_time": "Actual time: Not tracked yet",
    "projects.cycle": "Active Cycle",
    "projects.cycle_optional": "Projects remain valid without a Cycle connection.",
    "projects.open_cycle": "Open Cycle",
    "projects.milestone_target": "Target: {date}",
    "projects.blockers_title": "Blockers",
    "projects.blockers_empty": "No open blockers for this Project.",
    "projects.blocker_task": "Task: {task} - opened {date}",
    "projects.tasks_title": "Project Tasks",
    "projects.task_filter": "Task view",
    "projects.tasks_open": "Open",
    "projects.tasks_completed": "Completed",
    "projects.tasks_blocked": "Blocked",
    "projects.tasks_empty_filter": "No Tasks in this view.",
    "projects.tasks_none": "No Tasks in this Project yet.",
    "projects.quick_task": "Quick Task",
    "projects.status.active": "Active",
    "projects.status.on_hold": "On hold",
    "projects.status.completed": "Completed",
    "projects.status.archived": "Archived",
    "projects.favorite_add": "Add to Favorites",
    "projects.favorite_remove": "Remove from Favorites",
    "projects.card_no_description": "No description",
    "projects.card_open": "{count} open tasks",
    "projects.card_progress": "{count} in progress",
    "projects.card_blocked": "{count} blocked",
    "projects.last_activity": "Last activity · {date}",
    "projects.field_color": "Project color",
    "projects.field_status": "Project status",
    "projects.color_selected": "Selected color",
    "projects.create_title": "Create Project",
    "projects.create_description": "Create a new project space for goals, tasks, notes, and files.",
    "projects.edit_title": "Edit Project",
    "projects.edit_description": "Update the Project identity, color, and lifecycle state.",
    "projects.open_after_creation": "Open after creation",
    "projects.destination_stay": "Stay in Projects",
    "projects.destination_plan": "Plan",
    "projects.destination_tasks": "Tasks",
    "projects.scope_all": "Projects",
    "projects.scope_favorites": "Favorites",
    "projects.sort_recent": "Recently updated",
    "projects.sort_name": "Project name",
    "projects.sort_favorite": "Favorites first",
    "projects.next_checkpoint": "Next checkpoint",
    "projects.no_current_checkpoint": "No current checkpoint",
    "projects.linked_cycle": "Linked 12-Week Plan",
    "projects.no_linked_cycle": "No 12-week plan linked",
    "projects.cycle_week": "Week {week} of {length}",
    "projects.stages_total": "{count} stages total",
    "projects.stages_completed": "{count} stages completed",
    "projects.estimated_time": "Estimated · {value}",
    "projects.no_project_plan": "No active Project Plan yet.",
    "projects.plan_progress": "Plan progress",
    "projects.recent_updates": "Recent updates",
    "projects.recent_updates_empty": "No recent project activity",
    "projects.stages_total_label": "Stages total",
    "projects.stages_completed_label": "Stages completed",
    "projects.current_stage": "Current stage",
    "projects.current_stage_progress": "Current stage progress",
    "projects.overall_plan_progress": "Overall plan progress",
    "projects.stage_state.completed": "Completed",
    "projects.stage_state.not_started": "Not started",
    "projects.open_checkpoint": "Open checkpoint",
    "projects.open_next_action": "Open next action",
    "projects.open_linked_cycle": "Open linked 12-week plan",
    "projects.open_plan": "Open Project Plan",
    "projects.new_plan": "New Project Plan",
    "projects.plan_name": "Project Plan name",
    "projects.complete_plan": "Complete plan",
    "projects.project_goal": "Project goal",
    "projects.stages": "Stages",
    "projects.add_stage": "Add stage",
    "projects.stage_name": "Stage name",
    "projects.no_stages": "No Stages yet. Add the first major step when the Project Plan is ready.",
    "projects.stage_tasks": "{completed}/{total} tasks complete",
    "projects.stage_status.planned": "Planned",
    "projects.stage_status.in_progress": "In progress",
    "projects.stage_status.completed": "Completed",
    "projects.stage_status.archived": "Archived",
    "projects.tasks_all": "All Tasks",
    "projects.tasks_by_stage": "By Stage",
    "projects.search_tasks": "Search tasks",
    "projects.filter_stage_all": "All stages",
    "projects.sort_priority": "Sort priority",
    "projects.stage_empty": "No Tasks assigned to this Stage.",
    "projects.unassigned": "No Stage",
    "projects.task_summary": "Task Summary",
    "projects.create_task": "Create Task",
    "projects.notes": "Notes",
    "projects.files": "Files",
    "projects.new_note": "New note",
    "projects.add_file": "Add file",
    "projects.note_title": "Note title",
    "projects.note_content": "Markdown note",
    "projects.note_empty": "Empty note",
    "projects.notes_empty": "No notes yet.",
    "projects.files_empty": "No files yet.",
    "projects.note_preview": "Note preview",
    "projects.note_preview_empty": "Select or create a note to preview it here.",
    "projects.plan_history": "Plan history",
    "projects.plan_history_empty": "No completed or archived Project Plans yet.",
    "projects.what_archived": "What is archived?",
    "projects.archive_explainer": "Archiving removes a Project from active work without deleting its Tasks, Plans, Notes, Files, or history.",
    "projects.archive_project": "Archive Project",
    "projects.restore_project": "Restore Project",
    "projects.plan_status.active": "Active",
    "projects.plan_status.completed": "Completed",
    "projects.plan_status.archived": "Archived",
    "cycles.title": "12-Week Plans",
    "cycles.subtitle": "Plan a focused execution period around one meaningful Outcome.",
    "cycles.create_action": "Create Cycle",
    "cycles.browse": "Plans",
    "cycles.search": "Search Cycles",
    "cycles.status_filter": "Status",
    "cycles.status_all": "All statuses",
    "cycles.clear_filters": "Clear filters",
    "cycles.results_count": "{count} Cycles",
    "cycles.empty_filtered": "No Cycles match these filters.",
    "cycles.empty_all": "No 12-week plan yet. Create a focused Cycle when you are ready to organize several weeks around one meaningful Outcome.",
    "cycles.status.draft": "Draft",
    "cycles.status.active": "Active",
    "cycles.status.completed": "Completed",
    "cycles.status.archived": "Archived",
    "cycles.outcome_status.planned": "Planned",
    "cycles.outcome_status.achieved": "Achieved",
    "cycles.outcome_status.partial": "Partial",
    "cycles.outcome_status.not_achieved": "Not achieved",
    "cycles.milestone_status.planned": "Planned",
    "cycles.milestone_status.in_progress": "In progress",
    "cycles.milestone_status.completed": "Completed",
    "cycles.milestone_status.cancelled": "Cancelled",
    "cycles.main_outcome": "Main Outcome",
    "cycles.weekly_progress": "Weekly Outcomes",
    "cycles.connected_projects": "Connected Projects",
    "cycles.next_context": "Next",
    "cycles.open": "Open",
    "cycles.no_projects_compact": "No Projects connected",
    "cycles.no_milestone_compact": "No current Milestone",
    "cycles.week_of": "Week {week} of {length}",
    "cycles.progress_unavailable": "No Weekly Outcomes planned yet.",
    "cycles.progress_fraction": "{achieved} of {planned} planned Weekly Outcomes achieved",
    "cycles.progress_achieved": "{count} achieved",
    "cycles.progress_partial": "{count} partial",
    "cycles.progress_remaining": "{count} remaining",
    "cycles.progress_not_achieved": "{count} not achieved",
    "cycles.progress_unplanned": "{count} unplanned weeks",
    "cycles.create_title": "Create Cycle",
    "cycles.create_subtitle": "Shape the plan first. Nothing is saved until the final step.",
    "cycles.step.identity": "Identity",
    "cycles.step.dates": "Dates",
    "cycles.step.connections": "Connections",
    "cycles.step.weekly": "Weekly Outcomes",
    "cycles.step.review": "Review",
    "cycles.step_label": "{number}. {name}",
    "cycles.field_title": "Cycle title",
    "cycles.field_main_outcome": "Main Outcome",
    "cycles.main_outcome_help": "Describe the one result that would make this Cycle successful.",
    "cycles.title_required": "Cycle title is required.",
    "cycles.outcome_required": "Main Outcome is required.",
    "cycles.field_start": "Start date",
    "cycles.field_length": "Length in weeks",
    "cycles.date_error": "Start date must use YYYY-MM-DD.",
    "cycles.length_error": "Length must be a whole number of weeks.",
    "cycles.ends_value": "Ends {date}",
    "cycles.ends_pending": "Enter a valid start date and Cycle length.",
    "cycles.connections_help": "Connect only the Projects and existing Milestones that belong in this execution period.",
    "cycles.projects_section": "Projects",
    "cycles.projects_unavailable": "No Projects are available to connect.",
    "cycles.milestones_section": "Milestones",
    "cycles.milestones_unavailable": "No existing Milestones are available.",
    "cycles.stage_not_set": "Stage not defined",
    "cycles.unknown_project": "Unknown Project",
    "cycles.weekly_help": "Plan the weeks you understand now. Empty future weeks remain valid.",
    "cycles.week_number": "Week {number}",
    "cycles.week_outcome": "Weekly Outcome",
    "cycles.week_definition": "Definition of Done",
    "cycles.week_definition_required": "Definition of Done is required when an Outcome is planned.",
    "cycles.week_title_required": "Outcome text is required when Definition of Done is provided.",
    "cycles.week_error": "Week {number} needs both an Outcome and Definition of Done.",
    "cycles.length_value": "{count} weeks",
    "cycles.review_projects": "Projects: {value}",
    "cycles.review_milestones": "Milestones: {value}",
    "cycles.review_weekly": "{count} of {length} weeks have planned Outcomes",
    "cycles.review_week": "Week {number}: {title}",
    "cycles.none": "None",
    "cycles.active_conflict": "{title} is already active. This Cycle can be created as Draft, but activation requires resolving the existing active Cycle explicitly.",
    "cycles.cancel": "Cancel",
    "cycles.back": "Back",
    "cycles.continue": "Continue",
    "cycles.create_draft": "Create draft",
    "cycles.create_activate": "Create and activate",
    "cycles.created_draft": "Draft Cycle created.",
    "cycles.created_active": "Active Cycle created.",
    "cycles.unavailable": "Cycle unavailable",
    "cycles.all_cycles": "All 12-Week Plans",
    "cycles.outcome_unplanned": "Outcome not planned yet.",
    "cycles.not_set": "Not set",
    "cycles.edit": "Edit",
    "cycles.edit_week": "Edit Week {number}",
    "cycles.outcome_status": "Outcome status",
    "cycles.save_week": "Save Weekly Outcome",
    "cycles.week_updated": "Weekly Outcome updated.",
    "cycles.lifecycle_title": "Change Cycle status",
    "cycles.lifecycle_note": "Complete and Archive preserve the Cycle and its historical relationships.",
    "cycles.lifecycle_updated": "Cycle status updated.",
    "cycles.save": "Save",
    "cycles.current_week": "Current Week",
    "cycles.week_dates": "Week {number} - {start}-{end}",
    "cycles.connected_work": "Connected work: {projects} Projects - {tasks} open participating Tasks",
    "cycles.no_current_week": "This Cycle is outside its active date range.",
    "cycles.detail_progress": "{achieved} achieved - {partial} partial - {remaining} remaining - {missed} not achieved - {unplanned} unplanned weeks",
    "cycles.full_plan": "Full Cycle Plan",
    "cycles.project_milestone": "Current milestone: {value}",
    "cycles.project_open_tasks": "{count} open Tasks",
    "cycles.open_project": "Open Project",
    "cycles.no_projects": "No Projects connected. This Cycle remains valid.",
    "cycles.no_milestones": "No Milestones connected.",
    "cycles.connected_tasks": "Connected Task Context",
    "cycles.task_counts": "{open} open - {completed} completed - {total} connected",
    "cycles.task_context_note": "Tasks remain canonical Tasks; this is compact Cycle context, not another Tasks page.",
    "cycles.no_tasks": "No Tasks connected to this Cycle.",
    "cycles.more": "More",
    "recovery.page_title": "Overlord — Recovery",
    "recovery.icon": "Startup error",
    "recovery.title": "Overlord could not open safely",
    "recovery.description": "Normal write actions are disabled. The database was not automatically recreated or restored.",
    "recovery.error_id": "Error ID: {error_id}",
    "recovery.database": "Database: {database_path}",
    "recovery.category": "Category: {category}",
    "recovery.error_type": "Error type: {error_type}",
    "recovery.guidance": "Review data/backups and docs/architecture/DATABASE_RECOVERY.md before restoring anything.",
    "recovery.category.migration": "Migration or schema error",
    "recovery.category.integrity": "Database integrity error",
    "recovery.category.lock": "Database lock error",
    "recovery.category.permission": "Database permission error",
    "recovery.category.unexpected": "Unexpected startup error",
    "error.task_title_required": "Task title is required.",
    "error.project_title_required": "Project title is required.",
    "error.blocker_description_required": "Blocker description is required.",
    "error.blocker_resolution_required": "Blocker resolution is required.",
    "error.estimate_positive": "Estimate must be a positive number of minutes.",
    "error.task_missing": "Task {id} does not exist.",
    "error.project_missing": "Project {id} does not exist.",
    "error.blocker_missing": "Open Blocker {id} does not exist.",
    "error.cycle_missing": "Cycle {id} does not exist.",
    "error.slot_occupied": "That planning slot is already occupied.",
    "error.created_project_missing": "Created Project could not be loaded.",
    "error.created_task_missing": "Created Task could not be loaded.",
    "error.settings_missing": "Settings row is missing.",
    "error.week_repeated": "Week {number} is repeated.",
    "error.active_cycle_draft": "{title} is already active. Create this Cycle as Draft instead.",
    "error.active_cycle_replace": "{title} is already active. Complete or archive it before activating another Cycle.",
    "error.selected_projects_missing": "One or more selected Projects no longer exist.",
    "error.selected_milestones_missing": "One or more selected Milestones no longer exist.",
    "error.milestone_project_required": "A selected Milestone requires its Project to be connected.",
    "error.cycle_project_missing": "Cycle or Project does not exist.",
    "error.cycle_task_missing": "Cycle or Task does not exist.",
    "error.archived_cycle_read_only": "Archived Cycles are read-only until restored.",
    "error.missed_derived": "Not completed is automatic. Set an expired end time or deadline in the Task window.",
    "error.cycle_length": "Cycle length must be between 1 and 52 weeks.",
    "error.field_required": "This field is required.",
    "error.week_number_range": "Week number must be between 1 and {length}.",
    "error.definition_required": "Definition of Done is required before this action.",
    "error.primary_capacity": "A daily plan can contain at most 3 Primary Tasks.",
    "error.secondary_capacity": "A daily plan can contain at most 4 Secondary Tasks.",
    "error.daily_duplicate": "A Task can appear only once in a daily plan.",
    "error.plan_group_position": "Today group and position must be provided together.",
    "error.primary_position": "Primary position must be from 1 to 3.",
    "error.secondary_position": "Secondary position must be from 1 to 4.",
}


from overlord.ui.locales import MONTH_NAMES, RUSSIAN_STRINGS, SHORT_MONTHS, WEEKDAY_INITIALS, WEEKDAY_NAMES


SUPPORTED_LOCALES = ("en", "ru")
_CURRENT_LOCALE = "en"
CATALOGS = {"en": ENGLISH_STRINGS, "ru": RUSSIAN_STRINGS}


def set_locale(locale: str) -> None:
    global _CURRENT_LOCALE
    if locale not in SUPPORTED_LOCALES:
        raise ValueError(ENGLISH_STRINGS["settings.validation.language"])
    _CURRENT_LOCALE = locale


def get_locale() -> str:
    return _CURRENT_LOCALE


def ui_text(key: str, **values: object) -> str:
    template = CATALOGS[get_locale()][key]
    return template.format(**values) if values else template


def format_short_date(value: date) -> str:
    if get_locale() == "ru":
        return f"{value.day} {SHORT_MONTHS['ru'][value.month - 1]}"
    return f"{SHORT_MONTHS['en'][value.month - 1]} {value.day:02d}"


def format_compact_datetime(value) -> str:
    month = SHORT_MONTHS[get_locale()][value.month - 1]
    return f"{value.day} {month}., {value.strftime('%H:%M')}"


def format_dashboard_date(value: date) -> str:
    month = SHORT_MONTHS[get_locale()][value.month - 1]
    if get_locale() == "ru":
        return f"{value.day} {month}."
    suffix = "th" if 10 < value.day % 100 < 14 else {1: "st", 2: "nd", 3: "rd"}.get(value.day % 10, "th")
    return f"{value.day}{suffix} {month}."


def format_dashboard_week_range(start: date, end: date) -> str:
    if get_locale() == "ru":
        start_month = SHORT_MONTHS["ru"][start.month - 1]
        end_month = SHORT_MONTHS["ru"][end.month - 1]
        if start.year == end.year and start.month == end.month:
            return f"{start.day} - {end.day} {end_month}."
        return f"{start.day} {start_month}. - {end.day} {end_month}."

    def ordinal(day: int) -> str:
        suffix = "th" if 10 < day % 100 < 14 else {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")
        return f"{day}{suffix}"

    start_month = SHORT_MONTHS["en"][start.month - 1]
    end_month = SHORT_MONTHS["en"][end.month - 1]
    if start.year == end.year and start.month == end.month:
        return f"{ordinal(start.day)} - {ordinal(end.day)} {end_month}."
    return f"{ordinal(start.day)} {start_month}. - {ordinal(end.day)} {end_month}."


def format_long_date(value: date) -> str:
    locale = get_locale()
    if locale == "ru":
        return f"{WEEKDAY_NAMES['ru'][value.weekday()]}, {value.day} {MONTH_NAMES['ru'][value.month - 1]}"
    return f"{WEEKDAY_NAMES['en'][value.weekday()]}, {MONTH_NAMES['en'][value.month - 1]} {value.day:02d}"


def format_date_with_year(value: date) -> str:
    if get_locale() == "ru":
        return f"{value.day} {SHORT_MONTHS['ru'][value.month - 1]} {value.year}"
    return f"{SHORT_MONTHS['en'][value.month - 1]} {value.day:02d}, {value.year}"


def format_weekday_initial(value: date) -> str:
    return WEEKDAY_INITIALS[get_locale()][value.weekday()]


def format_weekday_name(value: date) -> str:
    return WEEKDAY_NAMES[get_locale()][value.weekday()]


def format_month_year(value: date) -> str:
    return f"{MONTH_NAMES[get_locale()][value.month - 1]} {value.year}"


_ERROR_PATTERNS = (
    (re.compile(r"^Task title is required\.$"), "error.task_title_required", ()),
    (re.compile(r"^Project title is required\.$"), "error.project_title_required", ()),
    (re.compile(r"^Blocker description is required\.$"), "error.blocker_description_required", ()),
    (re.compile(r"^Blocker resolution is required\.$"), "error.blocker_resolution_required", ()),
    (re.compile(r"^Estimate must be a positive number of minutes\.$"), "error.estimate_positive", ()),
    (re.compile(r"^Default cycle length must be between 1 and 52 weeks\.$"), "settings.validation.cycle_length", ()),
    (re.compile(r"^Theme mode must be System, Light, or Dark\.$"), "settings.validation.theme", ()),
    (re.compile(r"^Language must be English or Russian\.$"), "settings.validation.language", ()),
    (re.compile(r"^Task (\d+) does not exist\.$"), "error.task_missing", ("id",)),
    (re.compile(r"^Project (\d+) does not exist\.$"), "error.project_missing", ("id",)),
    (re.compile(r"^Open Blocker (\d+) does not exist\.$"), "error.blocker_missing", ("id",)),
    (re.compile(r"^Cycle (\d+) does not exist\.$"), "error.cycle_missing", ("id",)),
    (re.compile(r"^That planning slot is already occupied\.$"), "error.slot_occupied", ()),
    (re.compile(r"^Created Project could not be loaded\.$"), "error.created_project_missing", ()),
    (re.compile(r"^Created Task could not be loaded\.$"), "error.created_task_missing", ()),
    (re.compile(r"^Settings row is missing\.$"), "error.settings_missing", ()),
    (re.compile(r"^Week (\d+) is repeated\.$"), "error.week_repeated", ("number",)),
    (re.compile(r'^"(.+)" is already active\. Create this Cycle as Draft instead\.$'), "error.active_cycle_draft", ("title",)),
    (re.compile(r'^"(.+)" is already active\. Complete or archive it before activating another Cycle\.$'), "error.active_cycle_replace", ("title",)),
    (re.compile(r"^One or more selected Projects no longer exist\.$"), "error.selected_projects_missing", ()),
    (re.compile(r"^One or more selected Milestones no longer exist\.$"), "error.selected_milestones_missing", ()),
    (re.compile(r"^A selected Milestone requires its Project to be connected\.$"), "error.milestone_project_required", ()),
    (re.compile(r"^Cycle or Project does not exist\.$"), "error.cycle_project_missing", ()),
    (re.compile(r"^Cycle or Task does not exist\.$"), "error.cycle_task_missing", ()),
    (re.compile(r"^Archived Cycles are read-only until restored\.$"), "error.archived_cycle_read_only", ()),
    (re.compile(r"^Not completed is derived from an expired end time or deadline\.$"), "error.missed_derived", ()),
    (re.compile(r"^Cycle length must be between 1 and 52 weeks\.$"), "error.cycle_length", ()),
    (re.compile(r"^.+ is required\.$"), "error.field_required", ()),
    (re.compile(r"^Week number must be between 1 and (\d+)\.$"), "error.week_number_range", ("length",)),
    (re.compile(r"^Definition of Done is required before .+\.$"), "error.definition_required", ()),
    (re.compile(r"^A daily plan can contain at most 3 Primary Tasks\.$"), "error.primary_capacity", ()),
    (re.compile(r"^A daily plan can contain at most 4 Secondary Tasks\.$"), "error.secondary_capacity", ()),
    (re.compile(r"^A Task can appear only once in a daily plan\.$"), "error.daily_duplicate", ()),
    (re.compile(r"^Today group and position must be provided together\.$"), "error.plan_group_position", ()),
    (re.compile(r"^Primary position must be from 1 to 3\.$"), "error.primary_position", ()),
    (re.compile(r"^Secondary position must be from 1 to 4\.$"), "error.secondary_position", ()),
)


def ui_error(error: Exception | str) -> str:
    message = str(error)
    for pattern, key, names in _ERROR_PATTERNS:
        match = pattern.fullmatch(message)
        if match:
            values = dict(zip(names, match.groups(), strict=True))
            return ui_text(key, **values)
    return message
