from __future__ import annotations

from typing import Protocol

from overlord.modules.projects.domain import Project, ProjectStatus
from overlord.modules.projects.read_models import ProjectDetail


class ProjectRepositoryPort(Protocol):
    def create(self, title: str, description: str = "", status: ProjectStatus = ProjectStatus.ACTIVE) -> Project: ...
    def get(self, project_id: int) -> Project | None: ...
    def list(self, status: ProjectStatus | None = None, search: str = "") -> list[Project]: ...
    def detail(self, project_id: int) -> ProjectDetail | None: ...
    def update(self, project_id: int, **changes: object) -> Project: ...
