from __future__ import annotations

from typing import Protocol

from overlord.modules.projects.domain import (
    Project,
    ProjectPlan,
    ProjectPlanStatus,
    ProjectStage,
    ProjectStageStatus,
    ProjectStatus,
)
from overlord.modules.projects.read_models import ProjectDetail, ProjectFile, ProjectNote


class ProjectRepositoryPort(Protocol):
    def create(
        self,
        title: str,
        description: str = "",
        status: ProjectStatus = ProjectStatus.ACTIVE,
        *,
        color: str,
        favorite: bool = False,
    ) -> Project: ...
    def get(self, project_id: int) -> Project | None: ...
    def list(
        self,
        status: ProjectStatus | None = None,
        search: str = "",
        *,
        favorite_only: bool = False,
        sort: str = "recent",
    ) -> list[Project]: ...
    def detail(self, project_id: int) -> ProjectDetail | None: ...
    def update(self, project_id: int, **changes: object) -> Project: ...
    def create_plan(self, project_id: int, title: str) -> ProjectPlan: ...
    def get_plan(self, plan_id: int) -> ProjectPlan | None: ...
    def list_plans(self, project_id: int) -> list[ProjectPlan]: ...
    def update_plan(self, plan_id: int, status: ProjectPlanStatus) -> ProjectPlan: ...
    def create_stage(self, plan_id: int, project_id: int, title: str, **fields: object) -> ProjectStage: ...
    def get_stage(self, stage_id: int) -> ProjectStage | None: ...
    def list_stages(self, project_id: int, plan_id: int | None = None) -> list[ProjectStage]: ...
    def update_stage(self, stage_id: int, **changes: object) -> ProjectStage: ...
    def clear_stage_links(self, stage_id: int) -> None: ...
    def create_note(self, project_id: int, title: str, relative_path: str) -> ProjectNote: ...
    def list_notes(self, project_id: int) -> list[ProjectNote]: ...
    def create_file(self, project_id: int, display_name: str, relative_path: str, size_bytes: int) -> ProjectFile: ...
    def list_files(self, project_id: int) -> list[ProjectFile]: ...
