from __future__ import annotations

from pathlib import Path
from typing import Protocol


class ProjectWorkspacePort(Protocol):
    def write_note(self, project_id: int, title: str, content: str) -> str: ...
    def read_text(self, project_id: int, relative_path: str) -> str: ...
    def import_file(self, project_id: int, source: Path) -> tuple[str, int]: ...
    def remove(self, project_id: int, relative_path: str) -> None: ...
